hi

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -48,22 +48,39 @@ jobs:
 
       - name: Store Previous Lambda Version
         run: |
-          aws lambda get-alias --function-name demo-service-e --name prod > previous_version.json
-
+          set -e
+          if aws lambda get-alias --function-name demo-service-e --name prod > previous_version.json; then
+            echo "Alias found and version stored."
+          else
+            echo '{"AliasDescription":{"FunctionVersion":"1"}}' > previous_version.json
+            echo "Alias not found. Using default version 1."
+          fi
       - name: Terraform Apply
         run: |
           cd terraform
           terraform apply -auto-approve
+
+      - name: Create Alias If Missing
+        run: |
+          if ! aws lambda get-alias --function-name demo-service-e --name prod; then
+            LATEST_VERSION=$(aws lambda list-versions-by-function --function-name demo-service-e --query 'Versions[-1].Version' --output text)
+            aws lambda create-alias \
+              --function-name demo-service-e \
+              --name prod \
+              --function-version "$LATEST_VERSION"
+            echo "Alias 'prod' created pointing to version $LATEST_VERSION"
+          fi
+
       - name: Rollback on Failure
         if: failure()
         run: |
           PREV_VERSION=$(jq -r '.AliasDescription.FunctionVersion' previous_version.json)
           if [ -z "$PREV_VERSION" ]; then
-          echo "Previous version not found. Skipping rollback."
-          exit 1
+            echo "Previous version not found. Skipping rollback."
+            exit 0
           fi
           echo "Rolling back to version $PREV_VERSION"
           aws lambda update-alias \
-          --function-name demo-service-e \
-          --name prod \
-          --function-version "$PREV_VERSION"
+            --function-name demo-service-e \
+            --name prod \
+            --function-version "$PREV_VERSION"
