hi

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -57,8 +57,13 @@ jobs:
       - name: Rollback on Failure
         if: failure()
         run: |
-          PREV_VERSION=$(jq -r '.FunctionVersion' previous_version.json)
+          PREV_VERSION=$(jq -r '.AliasDescription.FunctionVersion' previous_version.json)
+          if [ -z "$PREV_VERSION" ]; then
+          echo "Previous version not found. Skipping rollback."
+          exit 1
+          fi
+          echo "Rolling back to version $PREV_VERSION"
           aws lambda update-alias \
           --function-name demo-service-e \
           --name prod \
-          --function-version $PREV_VERSION
+          --function-version "$PREV_VERSION"
